In [1]:
import numpy as np

In [2]:
ar = [1, 2, 3, 4, 5]
ar1 = ['k', 'p']

for i in ar:
    print(i)

1
2
3
4
5


In [3]:
import numpy as np

ar2 = np.array(ar)
print(ar2)

[1 2 3 4 5]


In [4]:
ar3 = np.array(ar1)
print(ar3)

['k' 'p']


In [5]:
type(ar)

list

In [6]:
type(ar1)

list

In [7]:
type(ar2)

numpy.ndarray

In [8]:
ss = ar2[2:]
print(ss)

[3 4 5]


In [9]:
arr = np.ones((3, 3))   

In [10]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr = np.ones(3)

In [12]:
arr

array([1., 1., 1.])

In [13]:
np.random.seed(0)  # seed for reproducibility

In [14]:
np.random.seed(6)

In [16]:
np.random.rand(10)

array([0.89286015, 0.33197981, 0.82122912, 0.04169663, 0.10765668,
       0.59505206, 0.52981736, 0.41880743, 0.33540785, 0.62251943])

In [19]:
empty_2d_array = np.empty((4, 3))

In [20]:
empty_2d_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
full_2d_array = np.full((3, 3), 7)

In [22]:
full_2d_array

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

Stack - LIFO

Insertion and deletion happen on same end

Push() - Insertion of an element Pop()

Deletions of he topmost elements empty()

Returns whether the stack is empty size()

size of stack peek()

top - a ref to the topmost elements of stack

In [23]:
stack = []
stack.append(1)
stack.append(2)
stack.append(3)
stack.append(4)
stack

[1, 2, 3, 4]

In [24]:
print(stack.pop(1))

2


In [25]:
stack

[1, 3, 4]

In [26]:
from collections import deque

queue = deque()
queue.append(1)
queue.append(2)
queue.append(3)
queue.append(4)
queue


deque([1, 2, 3, 4])

In [27]:
queue.pop()

4