<a href="https://colab.research.google.com/github/harshsinha-12/GoogleCollabTutorial/blob/main/Numpy3CampusX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)

In [3]:
b

array([[ 7, 63, 48, 66],
       [95, 26,  6, 84],
       [39, 78, 16, 83],
       [ 7, 28, 65, 61],
       [40,  5, 81, 40],
       [79, 30, 27, 90]])

In [4]:
np.sort(a)

array([ 4, 13, 21, 22, 24, 30, 33, 38, 42, 43, 59, 61, 79, 84, 98])

In [7]:
np.sort(a)[::-1] #descending

array([98, 84, 79, 61, 59, 43, 42, 38, 33, 30, 24, 22, 21, 13,  4])

In [5]:
np.sort(b) # row-wise

array([[ 7, 48, 63, 66],
       [ 6, 26, 84, 95],
       [16, 39, 78, 83],
       [ 7, 28, 61, 65],
       [ 5, 40, 40, 81],
       [27, 30, 79, 90]])

In [6]:
np.sort(b, axis = 0) # Column wise

array([[ 7,  5,  6, 40],
       [ 7, 26, 16, 61],
       [39, 28, 27, 66],
       [40, 30, 48, 83],
       [79, 63, 65, 84],
       [95, 78, 81, 90]])

# np.append

```
at end
```
The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html


In [8]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [9]:
np.append(a,200)

array([ 22,  38,  84,  33,  98,  42,  79,   4,  59,  61,  43,  21,  24,
        30,  13, 200])

In [10]:
b

array([[ 7, 63, 48, 66],
       [95, 26,  6, 84],
       [39, 78, 16, 83],
       [ 7, 28, 65, 61],
       [40,  5, 81, 40],
       [79, 30, 27, 90]])

In [11]:
np.append(b,np.ones((b.shape[0],1)))

array([ 7., 63., 48., 66., 95., 26.,  6., 84., 39., 78., 16., 83.,  7.,
       28., 65., 61., 40.,  5., 81., 40., 79., 30., 27., 90.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [13]:
np.append(b,np.ones((b.shape[0],1)), axis = 1)

array([[ 7., 63., 48., 66.,  1.],
       [95., 26.,  6., 84.,  1.],
       [39., 78., 16., 83.,  1.],
       [ 7., 28., 65., 61.,  1.],
       [40.,  5., 81., 40.,  1.],
       [79., 30., 27., 90.,  1.]])

# np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html



In [14]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [15]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
np.concatenate((c,d), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [18]:
np.concatenate((c,d), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((c,d)) # by default axis 0

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [25]:
e = np.array([1,2,3,4,5,1,2,3,4,5,6,1,2,3,4,5,3,2,3])

In [26]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [27]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [29]:
a.shape

(15,)

In [28]:
np.expand_dims(a,axis = 0)

array([[22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13]])

In [30]:
np.expand_dims(a,axis = 0).shape

(1, 15)

In [31]:
np.expand_dims(a,axis = 1)

array([[22],
       [38],
       [84],
       [33],
       [98],
       [42],
       [79],
       [ 4],
       [59],
       [61],
       [43],
       [21],
       [24],
       [30],
       [13]])

In [32]:
np.expand_dims(a,axis = 1).shape

(15, 1)

# np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [33]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [34]:
np.where(a>50)

(array([2, 4, 6, 8, 9]),)

In [35]:
# replace all values > 50 with 0
#np.where(condition, true, false)
np.where(a>50,0, a)

array([22, 38,  0, 33,  0, 42,  0,  4,  0,  0, 43, 21, 24, 30, 13])

In [36]:
np.where(a%2==0,0, a)

array([ 0,  0,  0, 33,  0,  0, 79,  0, 59, 61, 43, 21,  0,  0, 13])

# np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [37]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [38]:
np.argmax(a)

4

In [39]:
b

array([[ 7, 63, 48, 66],
       [95, 26,  6, 84],
       [39, 78, 16, 83],
       [ 7, 28, 65, 61],
       [40,  5, 81, 40],
       [79, 30, 27, 90]])

In [40]:
np.argmax(b,axis=0)

array([1, 2, 4, 5])

In [42]:
np.argmax(b,axis=1)

array([3, 0, 3, 2, 2, 3])

In [43]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [44]:
np.argmin(a)

7

# np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [45]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [46]:
np.cumsum(a)

array([ 22,  60, 144, 177, 275, 317, 396, 400, 459, 520, 563, 584, 608,
       638, 651])

In [47]:
b

array([[ 7, 63, 48, 66],
       [95, 26,  6, 84],
       [39, 78, 16, 83],
       [ 7, 28, 65, 61],
       [40,  5, 81, 40],
       [79, 30, 27, 90]])

In [49]:
np.cumsum(b)

array([   7,   70,  118,  184,  279,  305,  311,  395,  434,  512,  528,
        611,  618,  646,  711,  772,  812,  817,  898,  938, 1017, 1047,
       1074, 1164])

In [50]:
np.cumsum(b,axis = 0)

array([[  7,  63,  48,  66],
       [102,  89,  54, 150],
       [141, 167,  70, 233],
       [148, 195, 135, 294],
       [188, 200, 216, 334],
       [267, 230, 243, 424]])

In [51]:
np.cumsum(b,axis = 1)

array([[  7,  70, 118, 184],
       [ 95, 121, 127, 211],
       [ 39, 117, 133, 216],
       [  7,  35, 100, 161],
       [ 40,  45, 126, 166],
       [ 79, 109, 136, 226]])

In [52]:
np.cumprod(a) #cumilative product

array([                  22,                  836,                70224,
                    2317392,            227104416,           9538385472,
               753532452288,        3014129809152,      177833658739968,
          10847853183138048,   466457686874936064, -8651132649335894272,
       -4712998773256394752,  6183989391984570368,  6604885800961208320])

# np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [53]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [55]:
np.percentile(a,100)

98.0

In [56]:
np.percentile(a,77)

60.56

In [57]:
np.percentile(a,50)

38.0

In [58]:
np.percentile(a,0)

4.0

# np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [59]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [63]:
np.histogram(a,bins = [0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 3, 3, 2, 1, 1, 1, 1, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [64]:
salary = np.array([20000,40000,25000,35000,60000])
exp = np.array([1,3,2,4,2])

np.corrcoef(salary,exp)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [65]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [66]:
np.isin(a,[10,20,30,22,34,38])

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True, False])

In [67]:
a[np.isin(a,[10,20,30,22,34,38])]

array([22, 38, 30])

# np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [68]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [69]:
np.flip(a)

array([13, 30, 24, 21, 43, 61, 59,  4, 79, 42, 98, 33, 84, 38, 22])

In [70]:
b

array([[ 7, 63, 48, 66],
       [95, 26,  6, 84],
       [39, 78, 16, 83],
       [ 7, 28, 65, 61],
       [40,  5, 81, 40],
       [79, 30, 27, 90]])

In [72]:
np.flip(b)

array([[90, 27, 30, 79],
       [40, 81,  5, 40],
       [61, 65, 28,  7],
       [83, 16, 78, 39],
       [84,  6, 26, 95],
       [66, 48, 63,  7]])

In [73]:
np.flip(b,axis = 0)

array([[79, 30, 27, 90],
       [40,  5, 81, 40],
       [ 7, 28, 65, 61],
       [39, 78, 16, 83],
       [95, 26,  6, 84],
       [ 7, 63, 48, 66]])

In [74]:
np.flip(b,axis = 1)

array([[66, 48, 63,  7],
       [84,  6, 26, 95],
       [83, 16, 78, 39],
       [61, 65, 28,  7],
       [40, 81,  5, 40],
       [90, 27, 30, 79]])

# np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [75]:
a

array([22, 38, 84, 33, 98, 42, 79,  4, 59, 61, 43, 21, 24, 30, 13])

In [76]:
np.put(a,[0,1],[110,530]) #(a,index,value)

In [77]:
a

array([110, 530,  84,  33,  98,  42,  79,   4,  59,  61,  43,  21,  24,
        30,  13])

# np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [78]:
a

array([110, 530,  84,  33,  98,  42,  79,   4,  59,  61,  43,  21,  24,
        30,  13])

In [79]:
np.delete(a,0)

array([530,  84,  33,  98,  42,  79,   4,  59,  61,  43,  21,  24,  30,
        13])

In [80]:
np.delete(a,[0,2,4])

array([530,  33,  42,  79,   4,  59,  61,  43,  21,  24,  30,  13])

# Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [81]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [83]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [84]:
np.intersect1d(m,n)

array([3, 4, 5])

In [86]:
np.setdiff1d(m,n) # unique wrt n, m mein ho but n mein na ho

array([1, 2])

In [88]:
np.setxor1d(m,n) # remove the common elements

array([1, 2, 6, 7])

In [89]:
np.in1d(m,1)

array([ True, False, False, False, False])

In [90]:
np.in1d(m,10)

array([False, False, False, False, False])

In [91]:
m[np.in1d(m,10)]

array([], dtype=int64)

In [92]:
m[np.in1d(m,1)]

array([1])

# np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [93]:
a

array([110, 530,  84,  33,  98,  42,  79,   4,  59,  61,  43,  21,  24,
        30,  13])

In [95]:
np.clip(a,a_min = 25, a_max = 75)

array([75, 75, 75, 33, 75, 42, 75, 25, 59, 61, 43, 25, 25, 30, 25])

# Important for Interviews

In [96]:
# 17. np.swapaxes

In [97]:
# 18. np.uniform

In [98]:
# 19. np.count_nonzero

In [99]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [100]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [101]:
# 25. np.allclose and equals