<a href="https://colab.research.google.com/github/harshsinha-12/GoogleCollabTutorial/blob/main/Numpy1CampusX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Numpy Arrays

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3]) # 1D (Vector)

In [ ]:
a

array([1, 2, 3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a.shape

(3,)

In [ ]:
# 2D (Matrix)
b = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
b.shape

(3, 3)

In [ ]:
# 3D (Tensor)
c = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])

In [ ]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
print(type(c))

<class 'numpy.ndarray'>


In [ ]:
c.shape

(2, 2, 2)

In [ ]:
#dtype float
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [ ]:
#dtype bool
np.array([1,2,3], dtype = bool)

array([ True,  True,  True])

In [ ]:
#dtype complex
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.arange(1,17).reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [ ]:
np.arange(1,13).reshape(5,5)

ValueError: ignored

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.random.random((3,4)) # between 0 and 1

array([[0.40369101, 0.93511733, 0.10587409, 0.75735216],
       [0.72191498, 0.98543155, 0.3472622 , 0.37968759],
       [0.78074871, 0.11410717, 0.32928609, 0.46534082]])

In [28]:
# Create a random array of shape (3, 4) with numbers between 2 and 5
np.random.uniform(low=2, high=5, size=(3, 4))

array([[2.23886556, 4.55765374, 2.14884237, 3.18715032],
       [2.38173451, 3.48865293, 3.06466719, 4.35117507],
       [4.48348807, 3.25916101, 4.92312259, 2.20480688]])

In [29]:
np.linspace(-10,10,10) # low range,high range, total number of numbers...equidistant

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [30]:
np.linspace(-10,10,10,dtype = int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [31]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array Attributes

In [71]:
a = np.arange(10) # 1D Vector

In [75]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
b = np.arange(12,dtype = float).reshape(3,4) #2D Matrix

In [76]:
b

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [77]:
c = np.arange(8).reshape(2,2,2) # 3D Tensor

In [78]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [79]:
#ndim
a.ndim

1

In [80]:
b.ndim

2

In [81]:
c.ndim

3

In [82]:
a.shape

(10,)

In [83]:
b.shape

(3, 4)

In [84]:
c.shape

(2, 2, 2)

In [85]:
a.size

10

In [86]:
b.size

12

In [87]:
c.size

8

In [88]:
a.itemsize

8

In [89]:
b.itemsize

8

In [90]:
c.itemsize

8

In [91]:
a1 = np.arange(10,dtype = np.int32) # 1D Vector

In [92]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [93]:
a1.size

10

In [94]:
a1.itemsize

4

In [ ]:
# Int 32 -> 4 bytes
# Int 64 -> 8 bytes

In [95]:
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(a1.dtype)

int64
float64
int64
int32


# Change Data Type

In [96]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [97]:
c.dtype

dtype('int64')

In [98]:
c.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [100]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [101]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [103]:
#scalar operations
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [104]:
a1 + 3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [105]:
a1 - 3

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [106]:
a1/3

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667]])

In [107]:
# relational operators

a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [108]:
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [114]:
a1==5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [109]:
# vector operations
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [110]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [111]:
a1-a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [112]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [113]:
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [117]:
a1 = np.random.random((3,3))
a1

array([[0.00373163, 0.31621016, 0.93711067],
       [0.10435787, 0.1115452 , 0.7393047 ],
       [0.43968183, 0.05753419, 0.30459326]])

In [118]:
a1 = np.round(a1*100)

In [119]:
a1

array([[ 0., 32., 94.],
       [10., 11., 74.],
       [44.,  6., 30.]])

In [120]:
#max/min/prod
np.max(a1)

94.0

In [121]:
np.min(a1)

0.0

In [122]:
np.prod(a1) # product of all numbers

0.0

In [123]:
np.max(a1, axis = 0)

array([44., 32., 94.])

In [124]:
np.max(a1, axis = 1)

array([94., 74., 44.])

In [126]:
# Axis 0 = Column
# Axis 1 = Row
np.min(a1, axis = 1)

array([ 0., 10.,  6.])

In [127]:
np.prod(a1, axis = 1)

array([   0., 8140., 7920.])

In [128]:
np.mean(a1)

33.44444444444444

In [129]:
np.mean(a1, axis = 0)

array([18.        , 16.33333333, 66.        ])

In [130]:
np.mean(a1, axis = 1)

array([42.        , 31.66666667, 26.66666667])

In [131]:
np.var(a1)

929.1358024691357

In [132]:
np.std(a1)

30.481728994089814

In [133]:
np.median(a1)

30.0

In [134]:
np.sin(a1)

array([[ 0.        ,  0.55142668, -0.24525199],
       [-0.54402111, -0.99999021, -0.98514626],
       [ 0.01770193, -0.2794155 , -0.98803162]])

In [137]:
# Dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [138]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [139]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(3,4)

In [140]:
np.dot(a2,a3)

ValueError: ignored

In [141]:
# log and exponents
np.log(a1)

<ipython-input-141-928531e62f54>:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 3.4657359 , 4.54329478],
       [2.30258509, 2.39789527, 4.30406509],
       [3.78418963, 1.79175947, 3.40119738]])

In [142]:
np.exp(a1)

array([[1.00000000e+00, 7.89629602e+13, 6.66317622e+40],
       [2.20264658e+04, 5.98741417e+04, 1.37338298e+32],
       [1.28516001e+19, 4.03428793e+02, 1.06864746e+13]])

In [146]:
#round/floorlceil
a = np.random.random((2,3))

In [150]:
np.random.random((2,3))*100

array([[78.67814954, 37.41337889, 16.12931549],
       [30.95997991, 33.44509793, 65.85865302]])

In [147]:
a

array([[0.22042831, 0.78558536, 0.15129585],
       [0.48783855, 0.93979572, 0.87374876]])

In [153]:
b = a*100

In [154]:
b

array([[22.04283119, 78.5585359 , 15.12958525],
       [48.78385468, 93.97957227, 87.37487609]])

In [155]:
b.round() #roundoff to nearest int

array([[22., 79., 15.],
       [49., 94., 87.]])

In [159]:
np.floor(b) # to previous int

array([[22., 78., 15.],
       [48., 93., 87.]])

In [161]:
np.ceil(b) #to next int

array([[23., 79., 16.],
       [49., 94., 88.]])

# Indexing and Slicing

In [35]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [36]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a1[-1]

9

In [39]:
a1[0]

0

In [40]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a2[1]

array([4, 5, 6, 7])

In [42]:
a2[:,1]

array([1, 5, 9])

In [43]:
a2[1,2]

6

In [44]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
a3[1,0,1]

5

In [46]:
a3[0,1,0]

2

In [47]:
a3[0,0,0]

0

In [48]:
a3[1,1,0]

6

In [51]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a1[:3]

array([0, 1, 2])

In [50]:
a1[2:5:2]

array([2, 4])

In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
a2[0,:]

array([0, 1, 2, 3])

In [55]:
a2[:,2]

array([ 2,  6, 10])

In [56]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [57]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

# Iterating

In [58]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a3 = np.arange(0,27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [63]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [68]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [70]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [72]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
a2.shape

(3, 4)

In [78]:
#Transpose
aT = a2.T
aT

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [79]:
aT.shape

(4, 3)

In [81]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [80]:
# ravel

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking - Shape should be same

In [85]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [86]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [88]:
# Horizontal Stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [89]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [90]:
# Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting (opposite of Stacking)

In [91]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
# Horizontal Splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [93]:
# Verticle Splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]