<a href="https://colab.research.google.com/github/harshsinha-12/GoogleCollabTutorial/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
import numpy as np

In [19]:
myarr = np.array([3,4,5,6,7], np.int8)

In [20]:
myarr

array([3, 4, 5, 6, 7], dtype=int8)

In [21]:
myarr = np.array([3,4,5,6454535,7], np.int8)

In [22]:
myarr

array([3, 4, 5, 7, 7], dtype=int8)

In [23]:
myarr = np.array([3,4,5,6454535,7], np.int64)

In [24]:
myarr

array([      3,       4,       5, 6454535,       7])

# Hence we got Memory management in hands...can use int/float 8/16/32/64

In [26]:
myarr[0,1]
# Will give error as 1D array

IndexError: ignored

In [27]:
myarr = np.array([[3,4,5,6454535,7]], np.int64)

In [28]:
myarr[0,1]

4

In [29]:
myarr.shape

(1, 5)

In [30]:
myarr.dtype

dtype('int64')

In [31]:
myarr[0,1] = 45

In [32]:
myarr[0,1]

45

In [33]:
myarr

array([[      3,      45,       5, 6454535,       7]])

# Array Creation: Conversion from other Python Structures

In [34]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [35]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [36]:
la = np.array([[1,2,3],[5,8,5,6],[0,3,1]])

<ipython-input-36-04473ff930ae>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  la = np.array([[1,2,3],[5,8,5,6],[0,3,1]])


In [37]:
la

array([list([1, 2, 3]), list([5, 8, 5, 6]), list([0, 3, 1])], dtype=object)

In [38]:
listarray.dtype

dtype('int64')

In [39]:
listarray.shape

(3, 3)

In [40]:
listarray.size

9

In [41]:
np.array({23,4,6})

array({4, 6, 23}, dtype=object)

In [42]:
zeros = np.zeros((2,5))

In [43]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
zeros.dtype

dtype('float64')

In [45]:
zeros.shape

(2, 5)

# A range creates a Numpy array from 0 to n-1

In [46]:
rng = np.arange(15)

In [47]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
lspace = np.linspace(1,5,12)

In [49]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [50]:
lspace = np.linspace(1,50,10)

In [51]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [52]:
lspace = np.linspace(1,4,4)

In [53]:
lspace

array([1., 2., 3., 4.])

In [54]:
lspace = np.linspace(1,5,4)

In [55]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

Empty Array with Random Numbers

In [56]:
emp = np.empty((4,6))

In [57]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

Empty araay but like lspace or whatever

In [58]:
emp_like = np.empty_like(lspace)

In [59]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

Identity matrix

In [60]:
ide = np.identity(45)

In [61]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [62]:
ide.shape

(45, 45)

In [63]:
arr = np.arange(99)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [65]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [67]:
arr.reshape(3,31) # 3 x 31 = 93 not 99 that's why

ValueError: ignored

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [69]:
arr = arr.reshape(3,33)

In [70]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [71]:
arr.ravel() # way of writing

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [72]:
arr.shape

(3, 33)

In [73]:
arr = arr.ravel()

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [75]:
arr.shape

(99,)

1D -> 1 Axis

2D -> 2 Axis

1D -> [1,2,3]

2D -> [[1,2,3],[4,5,6],[7,8,9]]

A      Axis 1
    
     r1 1.  2.  3.      
x   

     r2 4.  5.  6.  
i

     r3 7.  8.  9.
     
s


0

In [76]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [77]:
ar = np.array(x)

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
ar.sum(axis = 0)

array([12, 15, 18])

In [81]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [82]:
# Transpose
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [83]:
ar.flat

In [84]:
for i in ar.flat:
  print(i)

1
2
3
4
5
6
7
8
9


In [86]:
ar.ndim # Dimension

2

In [88]:
ar.size

9

In [89]:
ar.nbytes # Total bytes consumed by array

72

In [95]:
one = np.array([1,5,6,2,3])

In [96]:
one

array([1, 5, 6, 2, 3])

In [97]:
one.argmax #Attribute

<function ndarray.argmax>

In [98]:
one.argmax() #Method # Index of maximum element

2

In [99]:
one.argmin()

0

In [102]:
one.argsort() #index

array([0, 3, 4, 1, 2])

In [103]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
ar.argmin()

0

In [106]:
ar.argmax()

8

In [107]:
ar.argmax(axis = 0) #vertical

array([2, 2, 2])

In [108]:
ar.argmax(axis = 1) #horizontl

array([2, 2, 2])

In [109]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [110]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [111]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [112]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [115]:
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
ar2 = np.array([[1,2,1],
               [4,0,6],
               [8,1,0]])

In [119]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [120]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [121]:
#while in list
[66,77] + [67,55]

[66, 77, 67, 55]

In [123]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [124]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [125]:
ar.sum()

45

In [126]:
ar.max()

9

In [127]:
ar.min()

1

In [128]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
np.where(ar > 5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [131]:
type(np.where(ar > 5))

tuple

In [132]:
np.count_nonzero(ar)

9

In [133]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [134]:
ar[1,2] = 0

In [135]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [136]:
import sys

In [138]:
py_ar = [0,4,55,2]

In [139]:
np_ar = np.array(py_ar)

In [140]:
sys.getsizeof(1) * len(py_ar)

112

In [141]:
np_ar.itemsize * np_ar.size

32

In [142]:
np_ar.tolist()

[0, 4, 55, 2]