<a href="https://colab.research.google.com/github/harshsinha-12/GoogleCollabTutorial/blob/main/Tutorial%20Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1

In [17]:
import numpy as np


shape = (2, 3, 4)

# Create a 3D array filled with zeros
array_3d = np.zeros(shape)


print(array_3d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# Question 2

In [10]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5])

copied_array = np.copy(original_array)

print(copied_array)


[1 2 3 4 5]


In [9]:
# Using Slicing

import numpy as np

original_array = np.array([1, 2, 3, 4, 5])

copied_array = original_array[:]

print(copied_array)


[1 2 3 4 5]


In [8]:
# Uaing Numpy.array

import numpy as np


original_array = np.array([1, 2, 3, 4, 5])

copied_array = np.array(original_array)

print(copied_array)


[1 2 3 4 5]


# Question 3

In [22]:
import numpy as np


arr = np.array([9, 2, 5, 1, 7, 3, 8, 4, 6])

# Use the sort function to sort the array in ascending order
sorted_arr = np.sort(arr)
sorted_arrD = np.sort(arr)[::-1]


print("Original 1D Array:", arr)
print("Sorted 1D Array (Ascending Order):", sorted_arr)

print("Original 1D Array:", arr)
print("Sorted 1D Array (Descending Order):", sorted_arrD)



Original 1D Array: [9 2 5 1 7 3 8 4 6]
Sorted 1D Array (Ascending Order): [1 2 3 4 5 6 7 8 9]
Original 1D Array: [9 2 5 1 7 3 8 4 6]
Sorted 1D Array (Descending Order): [9 8 7 6 5 4 3 2 1]


# Question 4

In [6]:
import numpy as np


array = np.array([5, 2, 8, 1, 9, 3, 6])


min_value = np.min(array)

print("Minimum value in the array:", min_value)


Minimum value in the array: 1


# Question 5

In [5]:
import numpy as np


array1 = np.array([5, 10, 15, 20])
array2 = np.array([2, 4, 6, 8])


addition_result = array1 + array2


subtraction_result = array1 - array2


multiplication_result = array1 * array2


division_result = array1 / array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)
print("Division Result:", division_result)


Array 1: [ 5 10 15 20]
Array 2: [2 4 6 8]
Addition Result: [ 7 14 21 28]
Subtraction Result: [ 3  6  9 12]
Multiplication Result: [ 10  40  90 160]
Division Result: [2.5 2.5 2.5 2.5]


# Question 6

In [21]:
import numpy as np


sample_data = np.array([[1, 2, 3],[4, 5, 6]])


print("Original 2D Array:")
print(sample_data)


reshaped_data = sample_data.reshape(3, 2)

print("\nReshaped 2D Array:")
print(reshaped_data)



Original 2D Array:
[[1 2 3]
 [4 5 6]]

Reshaped 2D Array:
[[1 2]
 [3 4]
 [5 6]]


In [16]:
import numpy as np


array1 = np.array([5, 10, 15, 20])
array2 = np.array([2, 4, 6, 8])
array3 = np.array([1, 2, 3, 4])


s = array3 - array2 - array1
m = array1 * array2 * array3
d = array1/array2/array3
a = array1 + array2 + array3

print("Array 1:", array1)
print("Array 2:", array2)
print("Array 3:", array3)
print("Result of Subtraction:", s)
print("Result of Multiplication:", m)
print("Result of Division:", d)
print("Result of Addition:", a)



Array 1: [ 5 10 15 20]
Array 2: [2 4 6 8]
Array 3: [1 2 3 4]
Result of Subtraction: [ -6 -12 -18 -24]
Result of Multiplication: [ 10  80 270 640]
Result of Division: [2.5        1.25       0.83333333 0.625     ]
Result of Addition: [ 8 16 24 32]
